# Generated by Django 5.1.15 on 2026-09-21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="IrrigationDurationRevision",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("old_min", models.PositiveIntegerField()),
                ("new_min", models.PositiveIntegerField()),
                ("reason", models.CharField(max_length=500)),
                ("revised_at", models.DateTimeField(auto_now_add=True)),
                (
                    "cycle",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="duration_revisions",
                        to="core.irrigationcycle",
                    ),
                ),
            ],
            options={
                "ordering": ["-revised_at", "-id"],
            },
        ),
        migrations.AddConstraint(
            model_name="irrigationdurationrevision",
            constraint=models.CheckConstraint(
                condition=models.Q(("new_min__gt", 0)),
                name="duration_revision_new_positive",
            ),
        ),
        migrations.AddConstraint(
            model_name="irrigationdurationrevision",
            constraint=models.CheckConstraint(
                condition=models.Q(("new_min", models.F("old_min")), _negated=True),
                name="duration_revision_new_differs",
            ),
        ),
    ]
